export const ADD_USER_INFO = 'ADD_USER_INFO'

export const ADD_ALL_SUBSCRIBER = 'ADD_ALL_SUBSCRIBER'
export const ADD_ALL_SUBSCRTIPTION = 'ADD_ALL_SUBSCRIPTION'

export const ADD_SUBSCRIBER = 'ADD_SUBSCRIBER'
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION'

export const ADD_UPDATES = 'ADD_UPDATES'

export const ADD_FRIENDS_UPDATE = 'ADD_FRIENDS_UPDATE'